HEARTBEAT_TIMEOUT = 8
HEARTBEAT_INTERVAL = 6

ROLE_TYPE_ACTIVE = 0
ROLE_TYPE_PASSIVE = 1

CONN_STATE_CONNECTING = 0
CONN_STATE_CONNECTED = 1
CONN_STATE_DISCONNECTING = 2
CONN_STATE_DISCONNECTED = 3


class ConnBase:
    pass
